name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'ansible/**'
      - 'diagrams/**'
  pull_request:
    paths-ignore:
        - 'README.md'
        - 'ansible/**'
        - 'diagrams/**'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target tests --tag todo-app:tests .
    - run: docker run --env-file ./.env.test todo-app:tests
    - run: docker run --entrypoint poetry todo-app:tests run safety check
      continue-on-error: true

  deploy:
    name: Push and deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/module-12'}}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'
      - run: docker build --target production --tag danielharedevops/todo-app .
      - run: docker push danielharedevops/todo-app
      - run: cd terraform
      - run: terraform init
      - run: terraform apply -auto-approve -var prefix=danhar
      - run: curl -dH -X POST "$(terraform output -raw webhook_url)"